/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreNicheRouteImport } from './routes/explore.$niche'
import { Route as ExploreNicheWeekNumberRouteImport } from './routes/explore.$niche.$weekNumber'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreNicheRoute = ExploreNicheRouteImport.update({
  id: '/$niche',
  path: '/$niche',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreNicheWeekNumberRoute = ExploreNicheWeekNumberRouteImport.update({
  id: '/$weekNumber',
  path: '/$weekNumber',
  getParentRoute: () => ExploreNicheRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/explore/$niche': typeof ExploreNicheRouteWithChildren
  '/explore/$niche/$weekNumber': typeof ExploreNicheWeekNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/explore/$niche': typeof ExploreNicheRouteWithChildren
  '/explore/$niche/$weekNumber': typeof ExploreNicheWeekNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/explore/$niche': typeof ExploreNicheRouteWithChildren
  '/explore/$niche/$weekNumber': typeof ExploreNicheWeekNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/explore/$niche'
    | '/explore/$niche/$weekNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/explore/$niche' | '/explore/$niche/$weekNumber'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/explore/$niche'
    | '/explore/$niche/$weekNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$niche': {
      id: '/explore/$niche'
      path: '/$niche'
      fullPath: '/explore/$niche'
      preLoaderRoute: typeof ExploreNicheRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/$niche/$weekNumber': {
      id: '/explore/$niche/$weekNumber'
      path: '/$weekNumber'
      fullPath: '/explore/$niche/$weekNumber'
      preLoaderRoute: typeof ExploreNicheWeekNumberRouteImport
      parentRoute: typeof ExploreNicheRoute
    }
  }
}

interface ExploreNicheRouteChildren {
  ExploreNicheWeekNumberRoute: typeof ExploreNicheWeekNumberRoute
}

const ExploreNicheRouteChildren: ExploreNicheRouteChildren = {
  ExploreNicheWeekNumberRoute: ExploreNicheWeekNumberRoute,
}

const ExploreNicheRouteWithChildren = ExploreNicheRoute._addFileChildren(
  ExploreNicheRouteChildren,
)

interface ExploreRouteChildren {
  ExploreNicheRoute: typeof ExploreNicheRouteWithChildren
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreNicheRoute: ExploreNicheRouteWithChildren,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
